# Locale
export LC_ALL=fr_FR.UTF-8
export LANG=fr_FR.UTF-8

# CUDA
export PATH=$PATH:/usr/local/cuda/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/:/usr/local/cuda/extras/CUPTI/lib64

# Intel MKL (for numpy compilation):
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/intel/mkl/lib/intel64
